# Generated by Django 5.0.6 on 2024-10-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_bookingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testimonialModel',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='seat',
            new_name='classNumber',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='ageLimit',
            new_name='duration',
        ),
    ]
